// @ts-nocheck
import { useEffect, useMemo, useState } from "react";
import SectionHero from "../components/SectionHero"; import StatusBadge from "../components/StatusBadge"; import Icon from "../components/Icon"; import { ErrorPanel, LoadingPanel } from "../components/StatePanel"; import { getJson } from "../api";
export default function SwaggerPage() {
 const [summary,setSummary]=useState(null),[operations,setOperations]=useState([]),[query,setQuery]=useState(""),[method,setMethod]=useState("GET"),[error,setError]=useState(null);
 useEffect(()=>{Promise.all([getJson("/api/swagger/summary"),getJson("/api/swagger/operations")]).then(([s,o])=>{setSummary(s);setOperations(o.operations)}).catch(setError)},[]);
 const filtered=useMemo(()=>operations.filter((item)=>(!method||item.method===method)&&(!query||`${item.route} ${item.summary} ${item.tags.join(" ")}`.toLowerCase().includes(query.toLowerCase()))),[operations,query,method]);
 if(error)return <ErrorPanel error={error}/>; if(!summary)return <LoadingPanel label="Loading packaged Swagger inventory…"/>;
 return <section className="page-panel"><SectionHero icon="fa-solid fa-code" kicker="OpenAPI reference" title="FastDraft Swagger inventory" description="The Portal serves a source-derived Swagger inventory from the ASP.NET Core API. Upload and live URL refresh workflows remain a later increment."><div className="hero-metrics compact"><div><strong>{summary.operationCount}</strong><span>Operations</span></div><div><strong>{summary.getOperationCount}</strong><span>GET operations</span></div><div><strong>{summary.controllerCount}</strong><span>Controllers</span></div><div><strong>{summary.getControllerCount}</strong><span>GET controllers</span></div></div></SectionHero>
 <article className="content-card"><div className="card-heading"><div><h2>Method inventory</h2><p>Current operation counts from the packaged inventory.</p></div><a className="button-link" href="/api/swagger/operations" target="_blank" rel="noreferrer"><Icon name="fa-solid fa-download"/> JSON</a></div><div className="method-grid">{Object.entries(summary.byMethod).map(([name,count])=><button className={method===name?"active":""} key={name} onClick={()=>setMethod(method===name?"":name)}><span>{name}</span><strong>{count}</strong></button>)}</div></article>
 <article className="content-card"><div className="card-heading"><div><h2>Operation reference</h2><p>Showing {filtered.length} matching operations.</p></div><StatusBadge>{method||"All methods"}</StatusBadge></div><div className="filter-field"><Icon name="fa-solid fa-magnifying-glass"/><input value={query} onChange={(event)=>setQuery(event.target.value)} placeholder="Search path, summary or controller"/><span>{filtered.length}</span></div><div className="operation-list">{filtered.slice(0,443).map((item)=><article key={`${item.method}-${item.route}`}><span className={`method ${item.method.toLowerCase()}`}>{item.method}</span><div><code>{item.route}</code><strong>{item.summary||"No summary declared"}</strong><small><Icon name="fa-solid fa-layer-group"/> {item.tags.join(", ")} · responses {item.responses.join(", ")||"not declared"}</small></div></article>)}</div></article>
 <article className="content-card"><h2>Coverage baseline</h2><div className="callout info"><Icon name="fa-solid fa-route"/><div><strong>Foundation delivery</strong><p>The packaged framework baseline contains 294 Automation requests, including 220 Foundation requests. A live route-to-test coverage service will replace this static baseline in a later increment.</p></div></div></article></section>;
}
